SIGen
.NewSubGroup( "tool-stone" )
.NewItem( "tool-stone-pick" , 10 )
.NewItem( "tool-stone-axe" , 10 )
.NewItem( "tool-stone-spade" , 10 )
.NewItem( "tool-stone-hoe" , 10 )
.NewItem( "tool-stone-collection-package" , 10 )
.NewRecipe( "sibt-item-tool-stone-collection-package" )
.SetEnergy( 5 )
.SetEnabled( true )
.AddCosts( "sibt-item-tool-stone-pick" )
.AddCosts( "sibt-item-tool-stone-axe" )
.AddCosts( "sibt-item-tool-stone-spade" )
.AddCosts( "sibt-item-tool-stone-hoe" )
.AddResults( "sibt-item-tool-stone-collection-package" )
.NewItem( "tool-stone-hammer" , 10 )
.NewItem( "tool-stone-knife" , 10 )
.NewItem( "tool-stone-stick" , 10 )
.NewItem( "tool-stone-awl" , 10 )
.NewItem( "tool-stone-tool-package" , 10 )
.NewRecipe( "sibt-item-tool-stone-tool-package" )
.SetEnergy( 5 )
.SetEnabled( true )
.AddCosts( "sibt-item-tool-stone-hammer" )
.AddCosts( "sibt-item-tool-stone-knife" )
.AddCosts( "sibt-item-tool-stone-stick" )
.AddCosts( "sibt-item-tool-stone-awl" )
.AddResults( "sibt-item-tool-stone-tool-package" )
.NewItem( "tool-stone-hand-rubbing-package" , 10 )
.NewRecipe( "sibt-item-tool-stone-hand-rubbing-package" )
.SetEnergy( 5 )
.SetEnabled( true )
.AddCosts( "sibt-item-tool-stone-collection-package" )
.AddCosts( "sibt-item-tool-stone-tool-package" )
.AddResults( "sibt-item-tool-stone-hand-rubbing-package" )
.NewSubGroup( "tool-wooden" )
.NewItem( "tool-wooden-pick" , 10 )
.NewItem( "tool-wooden-axe" , 10 )
.NewItem( "tool-wooden-spade" , 10 )
.NewItem( "tool-wooden-hoe" , 10 )
.NewItem( "tool-wooden-collection-package" , 10 )
.NewItem( "tool-wooden-hammer" , 10 )
.NewItem( "tool-wooden-knife" , 10 )
.NewItem( "tool-wooden-stick" , 10 )
.NewItem( "tool-wooden-awl" , 10 )
.NewItem( "tool-wooden-tool-package" , 10 )
.NewItem( "tool-wooden-fork" , 10 )
.NewItem( "tool-wooden-bow" , 10 )
.NewItem( "tool-wooden-stake" , 10 )
.NewItem( "tool-wooden-hand-rubbing-package" , 10 )
.NewSubGroup( "tool-copper" )
.NewItem( "tool-copper-pick" , 10 )
.NewItem( "tool-copper-axe" , 10 )
.NewItem( "tool-copper-spade" , 10 )
.NewItem( "tool-copper-hoe" , 10 )
.NewItem( "tool-copper-collection-package" , 10 )
.NewItem( "tool-copper-hammer" , 10 )
.NewItem( "tool-copper-knife" , 10 )
.NewItem( "tool-copper-stick" , 10 )
.NewItem( "tool-copper-awl" , 10 )
.NewItem( "tool-copper-tool-package" , 10 )
.NewItem( "tool-copper-bolt-driver" , 10 )
.NewItem( "tool-copper-pliers" , 10 )
.NewItem( "tool-copper-saw" , 10 )
.NewItem( "tool-copper-scissors" , 10 )
.NewItem( "tool-copper-maintenance-package" , 10 )
.NewItem( "tool-copper-fork" , 10 )
.NewItem( "tool-copper-hand-rubbing-package" , 10 )
.NewSubGroup( "tool-iron" )
.NewItem( "tool-iron-pick" , 10 )
.NewItem( "tool-iron-axe" , 10 )
.NewItem( "tool-iron-spade" , 10 )
.NewItem( "tool-iron-hoe" , 10 )
.NewItem( "tool-iron-collection-package" , 10 )
.NewItem( "tool-iron-hammer" , 10 )
.NewItem( "tool-iron-knife" , 10 )
.NewItem( "tool-iron-stick" , 10 )
.NewItem( "tool-iron-awl" , 10 )
.NewItem( "tool-iron-tool-package" , 10 )
.NewItem( "tool-iron-bolt-driver" , 10 )
.NewItem( "tool-iron-pliers" , 10 )
.NewItem( "tool-iron-saw" , 10 )
.NewItem( "tool-iron-scissors" , 10 )
.NewItem( "tool-iron-maintenance-package" , 10 )
.NewItem( "tool-iron-fork" , 10 )
.NewItem( "tool-iron-pestle" , 10 )
.NewItem( "tool-iron-hand-rubbing-package" , 10 )
.NewSubGroup( "tool-tool" )
.NewItem( "tool-tool-needle-universal" , 10 )
.NewItem( "tool-tool-needle-tailor" , 10 )
.NewItem( "tool-tool-web" , 10 )
.NewItem( "tool-tool-web-strengthen" , 10 )
.NewItem( "tool-tool-completely-package" , 10 )